### ISSUE TITLE
hey, where is your scratch profile?

### ISSUE THREAD

**Issue by webbrowser11** [WojtekCodesToday/wojtekcodestoday#3]

**Comment by WojtekCodesToday** [comment]
right now at https://wojtekgame.is-a.dev/ and going to socials
(for some reason i can't put it as an URL otherwise it turns into an empty HTML page)

**Comment by webbrowser11** [comment]
it just sends me to scratch.mit.edu can you please just give me your profile link from here it would be so much easier for me!

**Comment by webbrowser11** [comment]
err i found it novemind
